In [1]:
import math

import numpy as np

max_n_cars_at_first_location = 20
max_n_cars_at_second_location = 20
max_n_cars_to_move = 5
lambda_requests_at_first_location = 3
lambda_requests_at_second_location = 4
lambda_returns_at_first_location = 3
lambda_returns_at_second_location = 2
gamma = 0.9
theta = 1

def poisson_probability(lambduh, n, max_n):
    assert lambduh > 0
    assert 0 <= n <= max_n

    if n == max_n:
        return 1 - sum([poisson_probability(lambduh, i, max_n) for i in range(max_n)])
    else:
        return lambduh ** n * math.exp(-lambduh) / math.factorial(n)

def new_state_value(n_cars_at_first_location, n_cars_at_second_location, v, a):
    assert 0 <= n_cars_at_first_location <= max_n_cars_at_first_location
    assert 0 <= n_cars_at_second_location <= max_n_cars_at_second_location
    assert a <= n_cars_at_first_location and -a <= n_cars_at_second_location

    morning_n_cars_at_first_location = min(n_cars_at_first_location - a, max_n_cars_at_first_location)
    max_n_cars_returned_at_first_location = max_n_cars_at_first_location - morning_n_cars_at_first_location
    morning_n_cars_at_second_location = min(n_cars_at_second_location + a, max_n_cars_at_second_location)
    max_n_cars_returned_at_second_location = max_n_cars_at_second_location - morning_n_cars_at_second_location

    new_value = 0.0
    for n_cars_requested_at_first_location in range(morning_n_cars_at_first_location + 1):
        for n_cars_returned_at_first_location in range(max_n_cars_returned_at_first_location + 1):
            for n_cars_requested_at_second_location in range(morning_n_cars_at_second_location + 1):
                for n_cars_returned_at_second_location in range(max_n_cars_returned_at_second_location + 1):
                    p_requests_at_first_location = poisson_probability(lambda_requests_at_first_location, n_cars_requested_at_first_location, morning_n_cars_at_first_location)
                    p_returns_at_first_location = poisson_probability(lambda_returns_at_first_location, n_cars_returned_at_first_location, max_n_cars_returned_at_first_location)
                    p_requests_at_second_location = poisson_probability(lambda_requests_at_second_location, n_cars_requested_at_second_location, morning_n_cars_at_second_location)
                    p_returns_at_second_location = poisson_probability(lambda_returns_at_second_location, n_cars_returned_at_second_location, max_n_cars_returned_at_second_location)
                    p = p_requests_at_first_location * p_returns_at_first_location * p_requests_at_second_location * p_returns_at_second_location
                    r = 10 * (n_cars_requested_at_first_location + n_cars_requested_at_second_location) - 2 * abs(a)
                    final_n_cars_at_first_location = morning_n_cars_at_first_location + n_cars_returned_at_first_location - n_cars_requested_at_first_location
                    final_n_cars_at_second_location = morning_n_cars_at_second_location + n_cars_returned_at_second_location - n_cars_requested_at_second_location
                    new_value += p * (r + gamma * v[final_n_cars_at_first_location, final_n_cars_at_second_location])
    return new_value

def update_values(v, pi):
    for n_cars_at_first_location in range(max_n_cars_at_first_location + 1):
        for n_cars_at_second_location in range(max_n_cars_at_second_location + 1):
            a = pi[n_cars_at_first_location, n_cars_at_second_location]
            v[n_cars_at_first_location, n_cars_at_second_location] = new_state_value(n_cars_at_first_location, n_cars_at_second_location, v, a)

def update_policy(v, pi):
    for n_cars_at_first_location in range(max_n_cars_at_first_location + 1):
        for n_cars_at_second_location in range(max_n_cars_at_second_location + 1):
            possible_actions = [a for a in range(-max_n_cars_to_move, max_n_cars_to_move + 1) if a <= n_cars_at_first_location and -a <= n_cars_at_second_location]
            pi[n_cars_at_first_location, n_cars_at_second_location] = possible_actions[np.argmax([new_state_value(n_cars_at_first_location, n_cars_at_second_location, v, a) for a in possible_actions])]

# Initialization
v = np.zeros((max_n_cars_at_first_location + 1, max_n_cars_at_second_location + 1))
pi = np.zeros((max_n_cars_at_first_location + 1, max_n_cars_at_second_location + 1), dtype=int)
                                         
# Policy Evaluation
def evaluate_policy(v, pi):
    delta = float('inf')
    while delta >= theta:
        old_v = np.copy(v)
        update_values(v, pi)
        delta = abs(v - old_v).max()
        print('v:\n', v[::-1])
        print('delta:', delta)

# Policy Improvement
def improve_policy(v, pi):
    policy_stable = False
    while not policy_stable:
        print('v:\n', v[::-1])
        print('pi:\n', pi[::-1])
        evaluate_policy(v, pi)
        old_pi = np.copy(pi)
        update_policy(v, pi)
        if (pi == old_pi).all():
            policy_stable = True

improve_policy(v, pi)
print('final v:\n', v[::-1])
print('final pi:\n', pi[::-1])

v:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0

v:
 [[186.98199432 197.43974246 208.31709298 219.1056273  229.5164605
  239.50440829 249.01318523 257.93739388 266.18802009 273.72216607
  280.53511987 286.64497875 292.0832463  296.89122305 301.11782365
  304.81444019 308.02429138 310.76299159 312.97194062 314.46641117
  315.1085425 ]
 [176.47977401 187.87229015 200.47419251 212.68894207 223.77789089
  233.94578998 243.43327923 252.2682889  260.39985711 267.79503275
  274.45428397 280.40075663 285.67125476 290.31278461 294.3820747
  297.94866941 301.11092278 304.01620624 306.75653148 309.0341194
  310.25485504]
 [161.53439501 173.55968506 187.3411592  200.54504716 212.09014549
  222.33266572 231.71650697 240.3633446  248.25078288 255.35721727
  261.69341959 267.29391839 272.20718541 276.49171804 280.21687843
  283.47315694 286.41076467 289.29310845 292.34644005 295.19309783
  296.86386369]
 [148.94989217 160.9404773  174.65587305 187.78851333 199.23635947
  209.32478352 218.48650961 226.84451295 234.38374376 241.09430247
  247.0015369

v:
 [[288.87980655 299.14859479 309.64477291 320.03818861 330.13770546
  339.91700229 349.35876409 358.42184671 367.07231401 375.29654424
  383.09475038 390.47158104 397.43037519 403.96960156 410.07687701
  415.71448596 420.79122207 425.12549305 428.43237246 430.42505322
  431.13835442]
 [282.72711115 293.53319189 305.0195176  316.23704882 326.74550403
  336.66373681 346.14343861 355.21739206 363.87068653 372.09243234
  379.88258244 387.24537937 394.18411481 400.69784937 406.77629956
  412.38904211 417.46923123 421.89454365 425.44902008 427.79832912
  428.77448335]
 [273.7724887  284.97321336 297.18603615 309.00895222 319.82545783
  329.8606796  339.38495161 348.48059269 357.14372674 365.36384784
  373.13987132 380.47534326 387.37349279 393.83428994 399.85025864
  405.39879777 410.43508632 414.88627288 418.59326692 421.18926323
  422.35409591]
 [265.37431163 276.62658542 288.93868348 300.85479946 311.7348215
  321.81328415 331.36989853 340.48754416 349.15952802 357.37297859
  365.12554

v:
 [[352.60194915 362.7621084  373.02670918 383.14330799 392.95179823
  402.41502603 411.52065835 420.25234713 428.60164573 436.57243323
  444.17574046 451.42346679 458.32383412 464.87690078 471.06620424
  476.84074443 482.0820151  486.56354662 489.94972326 491.93996383
  492.61819191]
 [348.70952404 359.20689792 370.09341033 380.728647   390.79586581
  400.3492705  409.48316326 418.22803547 426.58771301 434.5680519
  442.18009202 449.43552239 456.34240704 462.90080763 469.09483647
  474.87660455 480.13979067 484.68902113 488.22478898 490.41898556
  491.24459785]
 [342.99913786 353.74118176 365.07886881 376.09179732 386.35371522
  395.98522758 405.15529597 413.9260502  422.30887553 430.3104318
  437.94150129 445.21348754 452.13424734 458.70381121 464.90680604
  470.69788135 475.97994595 480.58039221 484.22562892 486.56721786
  487.49851029]
 [337.50119696 348.27538612 359.67499812 370.74669164 381.05106604
  390.71581408 399.91666929 408.71701149 417.12730649 425.1534072
  432.8057294

v:
 [[393.40628487 403.50013186 413.62255556 423.56676864 433.18926964
  442.44353761 451.3171466  459.80543238 467.91183711 475.64721035
  483.02569098 490.06067853 496.7615072  503.12910977 509.14732558
  514.76453397 519.8605088  524.20655495 527.46902878 529.36305937
  529.9936821 ]
 [390.89119436 401.20158556 411.72346314 422.00096067 431.78984827
  441.10226435 449.99437323 458.49169544 466.60564186 474.34841421
  481.73423615 488.77643974 495.48430003 501.85874606 507.88389447
  513.50987174 518.62371139 523.01559093 526.37374682 528.39588259
  529.11844215]
 [387.16882936 397.6357076  408.44627732 418.96568324 428.87947634
  438.24229648 447.15825916 455.67331263 463.8038732  471.56282343
  478.96438619 486.02185967 492.74449515 499.13322993 505.17239043
  510.81334374 515.94816842 520.3800138  523.81174819 525.92777282
  526.71615344]
 [383.50395339 393.99133647 404.84145004 415.39850401 425.33973589
  434.72442815 443.66117675 452.19690216 460.34762072 468.12589809
  475.5459

v:
 [[419.91662854 429.96876496 440.00166705 449.83706446 459.34163697
  468.4626338  477.18714764 485.51735394 493.46357264 501.040351
  508.2630342  515.14520822 521.69623739 527.91718338 533.79216288
  539.27017023 544.23241167 548.45339319 551.60698581 553.42307863
  554.01881965]
 [418.26952187 428.46260166 438.75552994 448.8079304  458.42084941
  467.57969837 476.31624585 484.6523428  492.60351528 500.18520688
  507.41283343 514.2999512  520.8558967  527.08173243 532.96174537
  538.44603345 543.42045365 547.67165867 550.88759869 552.78683443
  553.44215544]
 [415.80755917 426.10224652 436.58266247 446.79222751 456.48630451
  465.67788771 474.42993133 482.77759631 490.73969304 498.33213761
  505.57037542 512.46796983 519.03426627 525.27034517 531.16061887
  536.6559385  541.6453147  545.92360057 549.18797392 551.14828636
  551.84620594]
 [413.32716494 423.63515354 434.14122566 444.37522788 454.0871335
  463.29296555 472.05861244 480.41989563 488.39539671 496.00085884
  503.2517417

v:
 [[437.30554495 447.33093107 457.30640647 467.07196127 476.50077149
  485.53604482 494.16450459 502.39263932 510.23509205 517.70867759
  524.82939644 531.61082832 538.06223818 544.18468467 549.96245257
  555.34506471 560.21502069 564.34959009 567.42845311 569.19176588
  569.76431562]
 [436.21610971 446.33405976 456.48031944 466.38842125 475.8884031
  484.94852556 493.58486466 501.81684103 509.6625224  517.13931587
  524.26327139 531.0479519  537.50260617 543.62829437 549.40941231
  554.79620448 559.67422003 563.8287013  566.94857108 568.76653895
  569.378248  ]
 [434.56749876 444.75207079 455.02127803 465.032465   474.58567331
  483.66723921 492.31370446 500.55323192 508.40605158 515.88988632
  523.02081067 529.81239704 536.27390419 542.40640648 548.1943811
  553.58856041 558.47654897 562.64894735 565.80070702 567.65881008
  568.298489  ]
 [432.86138731 443.0546755  453.34069551 463.36789687 472.93278725
  482.02369056 490.67907794 498.92755141 506.78919623 514.28162672
  521.420931

v:
 [[448.78692198 458.79492505 468.73308014 478.45323821 487.83279214
  496.81231606 505.37828323 513.53997358 521.31482673 528.72111611
  535.77525081 542.4907878  548.8769093  554.9346583  560.64842608
  565.96809739 570.77706697 574.85450601 577.88402074 579.6125704
  580.16990228]
 [448.06038294 458.1295563  468.18057911 477.99495246 487.42154601
  496.41748504 504.98864554 513.15285793 520.92982711 528.33821901
  535.39447621 542.11214518 548.50039798 554.56027888 560.27625265
  565.59868127 570.41297687 574.50358591 577.56023124 579.32494629
  579.9081922 ]
 [446.94273182 457.05588229 467.1880697  477.07050508 486.53223761
  495.54231932 504.12014316 512.28931649 520.07097453 527.48399325
  534.5448325  541.26704589 547.65981274 553.72418716 559.4446877
  564.77199818 569.59288821 573.69534508 576.7730767  578.56433056
  579.16607226]
 [445.74666833 455.86557003 466.00885119 475.90185314 485.37129172
  494.38753118 502.9712398  511.14631658 518.93380238 526.35250216
  533.418885

v:
 [[456.40280255 466.39940464 476.31308164 486.0034622  495.3507042
  504.29365304 512.8186157  520.93670088 528.66718043 536.02928237
  543.03968137 549.71191676 556.05511388 562.07030341 567.74194601
  573.02016648 577.78895496 581.82874625 584.82574631 586.53140156
  587.07871822]
 [455.91451889 465.95172147 475.94031479 485.69323519 495.07170154
  504.02554242 512.55394532 520.67369612 528.4055711  535.76905924
  542.78085769 549.45449904 555.79910203 561.81569828 567.48879736
  572.76884124 577.54116063 581.58969596 584.60471853 586.33440288
  586.89893917]
 [455.14625967 465.21262812 475.25505351 485.05312016 494.45489265
  503.41810698 511.95091863 520.07394751 527.80891981 535.17546432
  542.19028997 548.86693427 555.21452093 561.23408819 566.91018136
  572.19345615 576.9701448  581.02653961 584.05555961 585.80286649
  586.37968672]
 [454.28797793 464.35815959 474.40794042 484.21301272 493.61989322
  502.58718823 511.1238997  519.25084165 526.98967802 534.35999062
  541.37849

v:
 [[461.47096238 471.46003773 481.35755431 491.02827495 500.35418281
  509.27298158 517.77086777 525.86015687 533.56133001 540.89424515
  547.87575195 554.51937775 560.83420994 566.82127075 572.46506658
  577.71588119 582.45809919 586.47299259 589.44848864 591.13900278
  591.67969643]
 [461.14008651 471.15619187 481.10358575 490.81594565 500.16264261
  509.08869132 517.58886469 525.67925873 533.38135657 540.71519008
  547.69762401 554.3421813  560.65794498 566.645938   572.29069934
  577.54272415 582.28729039 586.3080061  589.29550786 591.00203164
  591.554199  ]
 [460.60303426 470.63854629 480.62176095 490.364164   499.72636939
  508.65865223 517.16175419 525.25432368 532.95847646 540.29433766
  547.27877999 553.92532971 560.24307321 566.23303787 571.87978651
  577.13395666 581.88142686 585.90737198 588.90419295 590.62245283
  591.18280219]
 [459.96928422 470.00733303 479.995441   489.74250452 499.10810746
  508.04310399 516.54879935 524.64397138 532.35069456 539.68906279
  546.6759

v:
 [[464.8513068  474.83539001 484.72218798 494.37986853 503.69162546
  512.59440502 521.07433019 529.14451667 536.8262476  544.13979868
  551.10213563 557.72677776 564.02278725 569.99118068 575.61649477
  580.84911881 585.57369938 589.57206446 592.53328442 594.21374621
  594.75004265]
 [464.62488634 474.62700329 484.54707872 494.23254133 503.55816882
  512.46578465 520.94723429 529.01815611 536.70050195 544.01466363
  550.97761698 557.60287842 563.89950725 569.86852054 575.49447679
  580.72790643 585.45405244 589.45630239 592.42553557 594.11668429
  594.66064023]
 [464.24143805 474.25649766 484.20046334 493.90596382 503.24193453
  512.15370668 520.63710714 528.70947711 536.39319061 543.70870177
  550.67299176 557.29957926 563.59752581 569.56785145 575.1951306
  580.42998874 585.15806973 589.16380704 592.13925782 593.83823835
  594.38765496]
 [463.75732807 473.77407929 483.72130798 493.42991615 502.76815215
  511.68173338 520.16686271 528.24096779 535.92639518 543.24357816
  550.20950

v:
 [[467.10946326 477.09022459 486.9698901  496.61889327 505.92123345
  514.81335279 523.28132524 531.33879889 539.00759053 546.30825384
  553.25783175 559.86983824 566.1533187  572.10928594 577.72229686
  582.94281099 587.65564934 591.6430101  594.59472479 596.26849327
  596.80186172]
 [466.9525748  476.94538562 486.84728619 496.51485295 505.8264612
  514.72181164 523.19080199 531.24876611 538.91796767 546.21903797
  553.16902674 559.78144603 566.06533931 572.02171974 577.63515878
  582.85621032 587.57009406 591.56005071 594.51712108 596.19803283
  596.73652119]
 [466.67145677 476.67291309 486.59077232 496.2717248  505.59024233
  514.4883685  522.95866089 531.01759111 538.68770492 545.98967534
  552.94055566 559.55385945 565.8386317  571.79588755 577.4102091
  582.63221378 587.34738923 591.33967525 594.30090002 595.98704552
  596.52918337]
 [466.28725575 476.28984194 486.20988061 495.89290875 505.21293919
  514.11227347 522.58372038 530.64380935 538.31506785 545.61815494
  552.570125

v:
 [[468.61961567 478.59816151 488.47307008 498.11628584 507.4123454
  516.29735469 524.7573549  532.80634915 540.46651013 547.75857691
  554.69964394 561.30322164 567.57834418 573.52602188 579.13082506
  584.34326015 589.04826452 593.02828336 595.97365606 597.64295857
  598.17437331]
 [468.5091126  478.49571775 488.38549836 498.04113068 507.34338932
  516.23055959 524.6912403  532.7405622  540.40099691 547.69333546
  554.63467683 561.23853016 567.51392835 573.46188195 579.06697105
  584.2797652  588.9854685  592.96722367 595.91617923 597.59026075
  598.12510093]
 [468.29629808 478.2886847  488.18913744 497.85372148 507.16060062
  516.0496268  524.51117772 532.56114509 540.22218925 547.51512912
  554.45706608 561.0615103  567.33749571 573.28603416 578.89171287
  584.1051439  588.81171061 592.79502343 595.74675767 597.42434017
  597.96162171]
 [467.97888639 477.97202855 487.87393864 497.53991063 506.84780136
  515.73763528 524.1999581  532.25070024 539.9125098  547.20619637
  554.14886

v:
 [[469.63030021 479.60736611 489.47909702 499.11844674 508.41031076
  517.2905704  525.74524492 533.7885746  541.44296987 548.72929365
  555.66467478 562.26262132 568.53215994 574.47429929 580.07361868
  585.28065585 589.98042591 593.95553911 596.8966742  598.56299254
  599.09310179]
 [469.55078802 479.53324822 489.41493344 499.06259403 508.35860731
  517.24031328 525.69544313 533.73899193 541.39357021 548.68007568
  555.61564022 562.21377103 568.48349394 574.42581775 580.02532831
  585.23260561 589.93284336 593.90911877 596.85265229 598.52216992
  599.05457236]
 [469.38362594 479.36995535 489.25878286 498.91243445 508.21153999
  517.09448788 525.55019988 533.59418039 541.24916625 548.53607386
  555.47203672 562.0705627  568.34067832 574.28339327 579.88329817
  585.09100147 589.79181688 593.76913469 596.71452806 598.38638916
  598.92042585]
 [469.11090201 479.09773702 488.98753981 498.64212022 507.94190271
  516.82539109 525.2816196  533.32611856 540.98161662 548.26902394
  555.2054

v:
 [[536.6652017  542.99975533 548.70005482 553.92878316 558.80850309
  563.41038208 567.76920202 571.90205751 575.81824005 579.51721867
  582.97539374 586.12236475 588.81242405 590.82697184 594.06739844
  597.01256351 599.64200869 601.97635591 604.10060189 605.16119926
  605.51251201]
 [532.32999316 538.85576983 544.77035497 550.2194016  555.32276648
  560.15242548 564.74350027 569.11170527 573.26249012 577.1894995
  580.86234256 584.20277317 587.05495965 589.18846946 592.57249584
  595.68557289 598.53491852 601.12027023 603.44786816 604.59344392
  604.98766221]
 [527.88040263 534.58276684 540.69735609 546.35912671 551.68273304
  556.7382277  561.55976757 566.16115292 570.54414494 574.69746506
  578.58516341 582.12188265 585.14109263 588.73972926 590.92228298
  594.13706977 597.05262145 599.67555906 602.02214084 603.26821918
  603.69695313]
 [523.35744271 530.22925072 536.53646935 542.40553041 547.94459957
  553.22042625 558.26555115 563.09187846 567.69812715 572.06916692
  576.16462

v:
 [[541.54136093 547.75636704 553.33038311 558.44524315 563.22920428
  567.75866926 572.07623632 576.2083063  580.17342062 583.97762425
  587.59698364 590.94834358 593.85606591 596.05649548 599.41569685
  602.42315792 605.05138063 607.34449268 609.42654294 610.57706314
  610.95217251]
 [537.70213397 544.06694416 549.80918586 555.10186137 560.06864601
  564.78461685 569.29205082 573.6157073  577.77018042 581.75622889
  585.54467112 589.04682435 592.0795781  594.37014316 597.99938618
  601.32685264 604.31178414 606.9375588  609.24233538 610.41149377
  610.79895471]
 [533.46879484 539.99930655 545.92818203 551.41865494 556.58884286
  561.51156069 566.22776638 570.75952144 575.11649699 579.29343575
  583.25563817 586.90934818 590.06525247 594.00775507 596.29840282
  599.88033722 603.16097456 606.1109876  608.71098759 609.90436213
  610.30463194]
 [528.93347664 535.64494007 541.77769861 547.48366485 552.87378239
  558.01720809 562.95266016 567.69929294 572.26227303 576.63082578
  580.7648

v:
 [[543.88034276 550.09402692 555.66753385 560.78332938 565.57009813
  570.1045346  574.42942677 578.57134725 582.54914919 586.36939388
  590.00855964 593.38300185 596.31474917 598.53580141 601.86398874
  604.84420714 607.45052246 609.72786826 611.80044337 612.95399713
  613.3285227 ]
 [540.09196359 546.4546624  552.19537705 557.48779599 562.45598041
  567.17530902 571.68837964 576.02038205 580.18655603 584.18847866
  587.99753208 591.52445288 594.58340769 596.89660044 600.50692215
  603.81923832 606.78815538 609.39297995 611.67579197 612.84047415
  613.22167666]
 [535.91045905 542.43800093 548.36421331 553.8530221  559.02291799
  563.94706382 568.66688905 573.20513517 577.57240335 581.76447346
  585.74728289 589.42639398 592.60950405 596.54699468 598.86086877
  602.44795574 605.73711699 608.68789748 611.27831721 612.4618438
  612.85126561]
 [531.42628589 538.13386502 544.26276964 549.96560547 555.35370136
  560.49662032 565.4336805  570.18489836 574.75654284 579.13896389
  583.29267

v:
 [[545.42108217 551.63012867 557.19858336 562.30928401 567.09107217
  571.62063345 575.940624   580.07744087 584.04986693 587.86465319
  591.49874426 594.86904354 597.79791806 600.01732123 603.31794471
  606.27609971 608.86681088 611.13479975 613.20284657 614.35235449
  614.72496749]
 [541.66858069 548.02636249 553.76171449 559.04873957 564.01162458
  568.72571728 573.23351563 577.56013139 581.72087151 585.71761724
  589.52224493 593.04595275 596.10305328 598.415443   601.99966855
  605.29061315 608.24187046 610.83163578 613.10290826 614.26053594
  614.63763044]
 [537.52390034 544.04617224 549.9666125  555.44958486 560.61370319
  565.53211408 570.24620931 574.77876541 579.1405794  583.32781481
  587.30688207 590.98367904 594.16585488 598.08076952 600.39366629
  603.96377342 607.24062465 610.18072834 612.76151164 613.93586299
  614.31957466]
 [533.07636386 539.77820485 545.9008037  551.5972385  556.97899144
  562.11565423 567.04658286 571.7919277  576.35823855 580.73626922
  584.8869

v:
 [[545.98506073 552.19177176 557.75759161 562.86550835 567.64443085
  572.17104767 576.48797102 580.6215366  584.59050307 588.40169505
  592.0322488  595.3993324  598.32557292 600.5431138  603.83324374
  606.7831125  609.36808958 611.63276847 613.69930511 614.84687454
  615.21867475]
 [542.2461214  548.60149075 554.33412468 559.61829028 564.57822828
  569.2892783  573.79390145 578.11717777 582.27443369 586.26766015
  590.06893254 593.589685   596.64443195 598.95518617 602.52897234
  605.81135188 608.75569638 611.33991042 613.60721101 614.76195459
  615.13755422]
 [538.11538668 544.63514712 550.55275654 556.03275014 561.19379286
  566.10902545 570.81982115 575.34896061 579.70730175 583.89114238
  587.86708204 591.5412103  594.7213151  598.62657651 600.93775084
  604.50023938 607.77133777 610.70673706 613.28372891 614.45452003
  614.83624852]
 [533.681742   540.38093368 546.50054802 552.19384618 557.57237077
  562.70572148 567.63325964 572.37517152 576.93809487 581.31292243
  585.4607

v:
 [[549.85202175 556.31366948 562.16224052 567.55689646 572.60678378
  577.22663349 581.82836645 586.18607901 590.31571061 594.22125479
  597.89439956 601.30550745 604.59537547 607.58063123 610.10891896
  612.79678853 615.11383633 617.2031427  619.02290643 620.06254007
  620.39773004]
 [546.01197391 552.63317469 558.66072733 564.10615477 569.49871773
  574.54635142 579.12946208 583.72761239 588.08225054 592.20944881
  596.11328187 599.78544037 603.19620764 606.45291487 609.43913106
  611.97051105 614.65056062 616.98042029 618.81829387 619.87864064
  620.22769928]
 [541.78304163 548.57580571 554.56875144 560.59430868 565.99352935
  571.38088594 576.42335465 580.95282264 585.54397189 589.89221175
  594.01392348 597.91345117 601.58263066 604.99174581 608.19989285
  611.1874117  613.72456178 616.37403617 618.24074858 619.32482587
  619.68670253]
 [537.25189095 544.22334053 550.51146992 556.45968894 562.47988756
  567.82534203 573.20405316 578.23797151 582.71176822 587.29253401
  591.6309

v:
 [[551.56861647 558.10091693 564.03386451 569.52288326 574.67368601
  579.30261337 584.00535317 588.46506764 592.69523582 596.69728064
  600.46029476 603.95209409 607.22343651 610.27369862 612.85297425
  615.51625928 617.81430208 619.89142519 621.73940822 622.79093632
  623.1276399 ]
 [547.72255461 554.41623615 560.53063263 566.00956445 571.49784728
  576.64775254 581.26094726 585.96205837 590.42019451 594.64891208
  598.64970446 602.41171349 605.90278772 609.1589762  612.20878649
  614.78898256 617.44879902 619.75284423 621.6117419  622.67444932
  623.01816043]
 [543.48022661 550.34622793 556.38792122 562.50183949 567.96088614
  573.44735844 578.59532488 583.18563253 587.88380693 592.33896409
  596.56477635 600.56286748 604.32250285 607.81165383 611.04611544
  614.09468409 616.6761095  619.32241834 621.2047239  622.28432265
  622.63594665]
 [538.92977252 545.97379226 552.31780496 558.339982   564.45229279
  569.88810146 575.37162895 580.51651374 585.08288777 589.7770232
  594.22797

v:
 [[552.50057145 559.04959774 565.00376407 570.5179933  575.69743464
  580.32137366 585.05501973 589.54793428 593.81299862 597.85087613
  601.64971356 605.17614213 608.43532121 611.51501593 614.11884342
  616.76848308 619.05708972 621.12855711 622.99050464 624.04830356
  624.38598425]
 [548.66527525 555.37583061 561.51175956 566.9912345  572.50530133
  577.68448936 582.30065961 587.03379437 591.52619532 595.79077518
  599.82822806 603.62672428 607.15291296 610.40497723 613.48455484
  616.08887276 618.73687551 621.02826681 622.89821002 623.96283179
  624.30427939]
 [544.43235015 551.31508934 557.36079664 563.49676286 568.96598998
  574.47957149 579.65820263 584.26297194 588.99520513 593.48664724
  597.75025554 601.78677919 605.58444466 609.10996064 612.35173364
  615.430949   618.03599897 620.67758548 622.56969271 623.64842854
  623.9954979 ]
 [539.89007081 546.95035606 553.29984234 559.3352149  565.47083693
  570.9279762  576.44074382 581.61849584 586.21106689 590.94210534
  595.4322

v:
 [[552.93290284 559.49842689 565.46442831 570.98363497 576.16124769
  581.05773881 585.70380398 590.11280574 594.28723819 598.28537366
  602.07094509 605.58758553 608.84963683 611.92160056 614.62800568
  617.17059522 619.45833915 621.5289642  623.38763413 624.44350628
  624.78039494]
 [549.07479626 555.80078093 561.94788077 567.6580168  573.02845802
  578.14536907 583.04237842 587.68982438 592.09984624 596.27489198
  600.26594522 604.05166146 607.56826682 610.82425331 613.89623217
  616.60041289 619.14526683 621.43498397 623.30131748 624.36325427
  624.70327359]
 [544.81973423 551.71596151 558.05406869 563.96451687 569.63830159
  575.00899687 580.1123228  585.00941087 589.6595681  594.0720098
  598.248855   602.22900983 606.01566697 609.53265388 612.77962891
  615.85191844 618.5500255  621.09664727 622.98531952 624.06100982
  624.40619854]
 [540.25970323 547.33074348 553.86370458 560.03439876 565.94500555
  571.60461677 576.97548741 582.06276749 586.95855134 591.6114978
  596.027227

In [3]:
import math

import numpy as np

max_n_cars_at_first_location = 20
max_n_cars_at_second_location = 20
max_n_cars_to_move = 5
lambda_requests_at_first_location = 3
lambda_requests_at_second_location = 4
lambda_returns_at_first_location = 3
lambda_returns_at_second_location = 2
gamma = 0.9
theta = 1

def poisson_probability(lambduh, n, max_n):
    assert lambduh > 0
    assert 0 <= n <= max_n

    if n == max_n:
        return 1 - sum([poisson_probability(lambduh, i, max_n) for i in range(max_n)])
    else:
        return lambduh ** n * math.exp(-lambduh) / math.factorial(n)

def new_state_value(n_cars_at_first_location, n_cars_at_second_location, v, a):
    assert 0 <= n_cars_at_first_location <= max_n_cars_at_first_location
    assert 0 <= n_cars_at_second_location <= max_n_cars_at_second_location
    assert a <= n_cars_at_first_location and -a <= n_cars_at_second_location

    morning_n_cars_at_first_location = min(n_cars_at_first_location - a, max_n_cars_at_first_location)
    max_n_cars_returned_at_first_location = max_n_cars_at_first_location - morning_n_cars_at_first_location
    morning_n_cars_at_second_location = min(n_cars_at_second_location + a, max_n_cars_at_second_location)
    max_n_cars_returned_at_second_location = max_n_cars_at_second_location - morning_n_cars_at_second_location

    new_value = 0.0
    for n_cars_requested_at_first_location in range(morning_n_cars_at_first_location + 1):
        for n_cars_returned_at_first_location in range(max_n_cars_returned_at_first_location + 1):
            for n_cars_requested_at_second_location in range(morning_n_cars_at_second_location + 1):
                for n_cars_returned_at_second_location in range(max_n_cars_returned_at_second_location + 1):
                    p_requests_at_first_location = poisson_probability(lambda_requests_at_first_location, n_cars_requested_at_first_location, morning_n_cars_at_first_location)
                    p_returns_at_first_location = poisson_probability(lambda_returns_at_first_location, n_cars_returned_at_first_location, max_n_cars_returned_at_first_location)
                    p_requests_at_second_location = poisson_probability(lambda_requests_at_second_location, n_cars_requested_at_second_location, morning_n_cars_at_second_location)
                    p_returns_at_second_location = poisson_probability(lambda_returns_at_second_location, n_cars_returned_at_second_location, max_n_cars_returned_at_second_location)
                    p = p_requests_at_first_location * p_returns_at_first_location * p_requests_at_second_location * p_returns_at_second_location
                    final_n_cars_at_first_location = morning_n_cars_at_first_location + n_cars_returned_at_first_location - n_cars_requested_at_first_location
                    final_n_cars_at_second_location = morning_n_cars_at_second_location + n_cars_returned_at_second_location - n_cars_requested_at_second_location
                    r = 10 * (n_cars_requested_at_first_location + n_cars_requested_at_second_location) - 2 * (abs(a) if a <= 0 else a - 1) - 4 * ((final_n_cars_at_first_location > 10) + (final_n_cars_at_second_location > 10))
                    new_value += p * (r + gamma * v[final_n_cars_at_first_location, final_n_cars_at_second_location])
    return new_value

def update_values(v, pi):
    for n_cars_at_first_location in range(max_n_cars_at_first_location + 1):
        for n_cars_at_second_location in range(max_n_cars_at_second_location + 1):
            a = pi[n_cars_at_first_location, n_cars_at_second_location]
            v[n_cars_at_first_location, n_cars_at_second_location] = new_state_value(n_cars_at_first_location, n_cars_at_second_location, v, a)

def update_policy(v, pi):
    for n_cars_at_first_location in range(max_n_cars_at_first_location + 1):
        for n_cars_at_second_location in range(max_n_cars_at_second_location + 1):
            possible_actions = [a for a in range(-max_n_cars_to_move, max_n_cars_to_move + 1) if a <= n_cars_at_first_location and -a <= n_cars_at_second_location]
            pi[n_cars_at_first_location, n_cars_at_second_location] = possible_actions[np.argmax([new_state_value(n_cars_at_first_location, n_cars_at_second_location, v, a) for a in possible_actions])]

# Initialization
v = np.zeros((max_n_cars_at_first_location + 1, max_n_cars_at_second_location + 1))
pi = np.zeros((max_n_cars_at_first_location + 1, max_n_cars_at_second_location + 1), dtype=int)

# Policy Evaluation
def evaluate_policy(v, pi):
    delta = float('inf')
    print('delta:', delta)
    while delta >= theta:
        old_v = np.copy(v)
        update_values(v, pi)
        delta = abs(v - old_v).max()
        print('v:\n', v[::-1])
        print('delta:', delta)

# Policy Improvement
def improve_policy(v, pi):
    policy_stable = False
    while not policy_stable:
        print('v:\n', v[::-1])
        print('pi:\n', pi[::-1])
        evaluate_policy(v, pi)
        old_pi = np.copy(pi)
        update_policy(v, pi)
        if (pi == old_pi).all():
            policy_stable = True

improve_policy(v, pi)
print('final v:\n', v[::-1])
print('final pi:\n', pi[::-1])

v:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0

v:
 [[171.76998351 182.19446905 193.00142792 203.70681686 214.0309424
  223.92446697 233.33122462 242.15121375 250.30022802 257.73699761
  264.45585001 270.47270808 275.8167221  280.52724049 284.65197384
  288.24223567 291.34285796 293.97368093 296.08512612 297.50841955
  298.11853489]
 [162.00576297 173.29884389 185.70890785 197.74041237 208.69367899
  218.75104276 228.13275472 236.86319184 244.893786   252.19270758
  258.75930028 264.61441121 269.79238103 274.33815572 278.30705478
  281.76780271 284.81769652 287.60169028 290.21327267 292.37681882
  293.53470251]
 [148.18168544 160.06068431 173.56317087 186.50982529 197.88130532
  207.99943524 217.27320238 225.81440612 233.60132659 240.6129294
  246.85840399 252.36953151 257.19198391 261.3820171  265.00745713
  268.15749045 270.97926158 273.72855216 276.62709293 279.32436269
  280.90689215]
 [136.67464201 148.52143815 161.96173784 174.83915094 186.11404136
  196.07900079 205.13244535 213.38748604 220.829404   227.44820481
  233.266803

v:
 [[267.34432036 277.59532263 288.05332184 298.40028232 308.44927283
  318.17107605 327.54774347 336.5403096  345.11662813 353.26306595
  360.97838484 368.26519545 375.12495246 381.55494812 387.54283778
  393.05285059 397.99869217 402.20794497 405.40983039 407.33373423
  408.02029059]
 [261.59021324 272.34571852 283.73349717 294.85439273 305.28731875
  315.13928064 324.55104377 333.55306454 342.13103121 350.27382484
  357.97990591 365.2514575  372.08987384 378.49303362 384.45065602
  389.93400563 394.88004513 399.17274005 402.6069532  404.86734404
  405.80241731]
 [253.2990271  264.42449019 276.49338849 288.18190033 298.90341288
  308.86440418 318.31684538 327.33756215 335.92242914 344.0604591
  351.74888111 358.98900535 365.78207054 372.12689103 378.01609797
  383.42879395 388.32343885 392.63175945 396.20360903 398.69376172
  399.80633765]
 [245.70068217 256.87438069 269.03613545 280.81169569 291.59222544
  301.59285829 311.07415421 320.11317933 328.70274198 336.82905691
  344.48750

v:
 [[327.45508746 337.60490725 347.84726428 357.93664579 367.71522696
  377.14393373 386.20972302 394.89703316 403.19780454 411.11506835
  418.65801844 425.83633312 432.65623872 439.11656832 445.20096082
  450.86059662 455.98234805 460.3495946  463.64119723 465.571448
  466.22763192]
 [323.80880731 334.27696393 345.10644204 355.68548192 365.70831474
  375.22207788 384.31440253 393.01394141 401.32419639 409.25002469
  416.80057983 423.98529657 430.81022701 437.27421363 443.36148061
  449.02623066 454.16699088 458.59675224 462.02877803 464.15146132
  464.9469937 ]
 [318.5494338  329.24833727 340.50334237 351.43862842 361.64503513
  371.23226427 380.35833418 389.08166891 397.41276766 405.35705121
  412.92319894 420.12016932 426.95371377 433.42269031 439.51200505
  445.1785946  450.3302049  454.80205106 458.33275649 460.59211734
  461.48679567]
 [313.680361   324.40956174 335.72292186 346.71354552 356.95982419
  366.5780619  375.7325298  384.48260116 392.83753656 400.80146624
  408.382101

v:
 [[366.09768746 376.18527552 386.29420732 396.22182636 405.82591051
  415.05861663 423.90683997 432.36601846 440.43929452 448.13629389
  455.46918555 462.44911498 469.08340528 475.37174441 481.29805016
  486.81284658 491.80120419 496.04407065 499.22169779 501.06279126
  501.67458171]
 [363.74500337 374.03776984 384.52520045 394.76863467 404.53037323
  413.81813676 422.68380969 431.15142024 439.23163623 446.93532622
  454.27469341 461.26077702 467.90082047 474.19451356 480.12607355
  485.64774849 490.65159672 494.93661357 498.20398625 500.16602731
  500.86486007]
 [360.35596425 370.79690307 381.55769702 392.03020033 401.91016818
  411.24552483 420.13352191 428.61745545 436.71260223 444.43028717
  451.78248947 458.78001693 465.42999109 471.73215584 477.67111654
  483.20061148 488.21793083 492.53498755 495.86759428 497.91603909
  498.67645331]
 [357.22033139 367.68067836 378.47889249 388.98698899 398.8928098
  408.24860172 417.15573055 425.65818919 433.77051317 441.50320929
  448.86761

v:
 [[391.27346352 401.32170253 411.34618041 421.17114252 430.66397363
  439.7709549  448.47852877 456.78858879 464.71077115 472.25819689
  479.44418101 486.28005325 492.773173   498.92335544 504.71478073
  510.09854487 514.9610468  519.08621156 522.16132529 523.92898615
  524.50788049]
 [389.7400977  399.92223432 410.19374442 420.2248709  429.82062769
  438.9635395  447.68248517 455.99803588 463.92474708 471.47655266
  478.66678872 485.50671464 492.00363992 498.15738586 503.95233018
  509.3406828  514.21336124 518.36597558 521.49936564 523.34549327
  523.98084825]
 [387.54233486 397.82095253 408.27049374 418.45085324 428.12363139
  437.29751077 446.03093908 454.35704599 462.29337333 469.85411548
  477.05241421 483.89933752 490.402105   496.56060168 502.35951301
  507.75207586 512.63264637 516.80523289 519.98017833 521.88174753
  522.55675055]
 [385.53043862 395.82168236 406.29556887 416.49908518 426.18867381
  435.37582097 444.12163187 452.45963946 460.40680654 467.97664689
  475.1817

v:
 [[407.81981749 417.84272455 427.81281999 437.57164069 446.9927234
  456.01852173 464.63512772 472.84851922 480.67242685 488.12211992
  495.21153507 501.95199729 508.3507729  514.40767497 520.10704305
  525.40047271 530.17558529 534.21891868 537.22325609 538.94092035
  539.49784164]
 [406.81478219 416.92579121 427.05844019 436.95293895 446.44175509
  455.49117905 464.11523203 472.33218427 480.15899854 487.61146886
  494.70353277 501.44645704 507.84746908 513.90638867 519.60769658
  524.90373997 529.68514047 533.74616355 536.78855972 538.55769297
  539.15171933]
 [405.38831722 415.56271438 425.81234252 435.80491315 445.34432865
  454.41404713 463.04751522 471.27123832 479.10410309 486.56201546
  493.65871396 500.40527633 506.80884117 512.86928856 518.57136518
  523.86819336 528.65279172 532.72512905 535.7934245  537.59816685
  538.21798238]
 [404.11267195 414.29535931 424.56097008 434.56873296 444.11914818
  453.19749288 461.8389202  470.07012898 477.90950626 485.3723386
  492.471770

v:
 [[418.76028994 428.76668998 438.70134557 448.41705628 457.7913632
  466.76421886 475.32147733 483.47176701 491.23147415 498.61725333
  505.64342936 512.32130575 518.65807042 524.65352167 530.29210021
  535.52574525 540.24292809 544.23199246 547.18945066 548.87408896
  549.41655178]
 [418.09997071 428.16466994 438.20689608 448.01239917 457.43152905
  466.42000534 474.98216438 483.13476639 490.89632871 498.28384078
  505.31161302 511.99089669 518.32884642 524.32526694 529.96470448
  535.19961749 539.92049671 543.92085011 546.90318644 548.62172743
  549.18871037]
 [417.17821711 427.28481851 437.4043776  447.27471832 456.72728497
  465.72913177 474.29742571 482.4543473  490.21964272 497.61031278
  504.64046189 511.32114999 517.65944038 523.65519391 529.29319649
  534.52652394 539.24740083 543.25331165 546.25129156 547.99253012
  548.57630367]
 [416.38835126 426.50043021 436.63054661 446.51091168 455.97070693
  464.97816476 473.55153781 481.71305976 489.48202487 496.87485022
  503.90504

v:
 [[426.02459223 436.02014422 445.93150873 455.61888559 464.96244678
  473.9004998  482.41874031 490.52753659 498.24501828 505.58874824
  512.57330404 519.20997245 525.50588725 531.46083505 537.05932255
  542.25351745 546.93245765 550.88568951 553.81219978 555.47504609
  556.00797559]
 [425.59102438 435.62530749 445.60813871 455.35517359 464.72851204
  473.67693234 482.19840729 490.3087032  498.02735676 505.37214049
  512.35760704 518.99499443 525.29140655 531.2466361  536.84527187
  542.03984841 546.72077875 550.6810889  553.62380918 555.30900669
  555.85818036]
 [425.00195809 435.06405878 445.09823062 454.88830996 464.28383246
  473.24108949 481.76655786 489.87957599 497.60045224 504.94690366
  511.93327159 518.57060063 524.86590113 530.81901884 536.41476506
  541.60618877 546.2850029  550.24707828 553.19869854 554.89810963
  555.4581625 ]
 [424.53416924 434.59990477 444.64107947 454.43779746 463.83807863
  472.79897231 481.32763301 489.44335941 497.16603846 504.51282632
  511.4974

v:
 [[430.86215419 440.85053429 450.74650018 460.41514373 469.73837617
  478.653417   487.14585653 495.22721287 502.91676791 510.23268477
  517.18970775 523.79911219 530.06799574 535.99613695 541.56808611
  546.73616238 551.38977964 555.31928213 558.22529718 559.87371235
  560.40032925]
 [430.57859714 440.59277959 450.53635689 460.24474552 469.5878131
  478.5097517  487.00432789 495.08665063 502.7769301  510.09345609
  517.05094093 523.66061342 529.92954345 535.8575154  541.42914612
  546.59702078 551.25150208 555.1852991  558.10179022 559.76491345
  560.30229799]
 [430.20995044 440.24265525 450.22041786 459.95746514 469.31528962
  478.24307556 486.74023656 494.82423266 502.51574343 509.83295878
  516.79037607 523.39902915 529.66589281 535.59080241 541.15858594
  546.32227503 550.97324542 554.90630284 557.82723691 559.49896474
  560.04331958]
 [429.95642541 439.99154945 449.97397007 459.71542254 469.07637686
  478.00649783 486.5056072  494.59106365 502.28314527 509.59949604
  516.55401

v:
 [[434.09026244 444.07388097 453.95962328 463.61582893 472.92556384
  481.82532504 490.30063265 498.363768   506.03477793 513.33222402
  520.27096126 526.86225736 533.11318589 539.02352004 544.57783899
  549.72856259 554.3653546  558.27908968 561.17148564 562.81031095
  563.33273287]
 [433.90634745 443.90718848 453.8247106  463.5074452  472.83041681
  481.73477401 490.21149122 498.27524092 505.9466803  513.2444425
  520.18334577 526.7746127  533.02529052 538.93515801 544.48885062
  549.63898717 554.27589697 558.19207874 561.0911423  562.73959798
  563.26914881]
 [433.68426278 443.69746255 453.63779368 463.33964623 472.67244947
  481.58067306 490.05904328 498.12377348 505.79578949 513.09359502
  520.03179087 526.62140363 532.86938438 538.77556149 544.324774
  549.470042   554.10251737 558.0162985  560.91684697 562.57018325
  563.10410859]
 [433.57361462 443.58842776 453.53186245 463.23663968 472.57149326
  481.48118948 489.96068389 498.02604746 505.69781769 512.99396229
  519.9284776

v:
 [[436.24744904 446.2278969  456.10683138 465.75475455 475.05550122
  483.94508727 492.40898597 500.45998682 508.11864599 515.4037904
  522.33034874 528.90958363 535.14855262 541.04702528 546.58960008
  551.7287639  556.35434701 560.25757746 563.14089969 564.77333548
  565.29296229]
 [436.12990644 446.12186534 456.02204054 465.68769429 474.99728492
  483.88993504 492.35476004 500.40614172 508.06503492 515.35030135
  522.27682979 528.85583864 535.09436005 540.99216904 546.53391344
  551.67223445 556.29743914 560.20188603 563.0893391  564.72802252
  565.25235391]
 [436.00551888 446.0057358  455.92115091 465.59957437 474.91571964
  483.81091882 492.27677797 500.32868042 507.98771599 515.27259723
  522.1979938  528.77492744 535.01033337 540.90403532 546.44087963
  551.57387872 556.19403532 560.09497654 562.98194537 564.62302958
  565.15000665]
 [435.99030125 445.9915955  455.9090802  465.58944355 474.90692122
  483.80301961 492.26945493 500.32144081 507.97968745 515.26237802
  522.18357

v:
 [[437.69041486 447.66874703 457.54313884 467.18553529 476.48028422
  485.36308045 493.81936593 501.86226921 509.51268631 516.78962122
  523.7080518  530.27923726 536.51022447 542.40078059 547.93551694
  553.06696516 557.68506666 561.58128537 564.45855079 566.0867214
  566.60448232]
 [437.61717053 447.6032035  457.49180503 467.14606216 476.44672444
  485.3315629  493.78845257 501.83158131 509.4821025  516.7590304
  523.67730082 530.24812938 536.47853813 542.3682996  547.90206986
  553.03250505 557.64989736 561.54651171 564.42621492 566.05837522
  566.57922244]
 [437.55802097 447.54957735 457.4483711  467.11116421 476.41619574
  485.30270508 493.7602167  501.8035602  509.45393477 516.73019233
  523.64704845 530.21552159 536.44253643 542.32791354 547.85650418
  552.98131561 557.59325097 561.48562282 564.36352811 565.99643448
  566.51877363]
 [437.60661606 447.59889235 457.49906625 467.16314263 476.46902794
  485.35605424 493.81377674 501.85683706 509.50606058 516.77977423
  523.692087

v:
 [[438.65629041 448.63320883 458.50456509 468.14326838 477.43400938
  486.31226833 494.76346625 502.80095822 510.44586738 517.717316
  524.63031484 531.19612082 537.42177366 543.30703893 548.83653652
  553.96282799 558.57592902 562.46746123 565.34067831 566.96599803
  567.48251175]
 [438.61265212 448.5947256  458.47559394 468.12223593 477.4169322
  486.29655073 494.74813778 502.78575158 510.43067822 517.70203384
  524.6147857  531.18014756 537.40513472 543.28951804 548.81795907
  553.94312396 558.55529494 562.44667435 565.32119773 566.94899798
  567.46751632]
 [438.59711865 448.58288896 458.47057785 468.12292777 477.42053352
  486.3012365  494.7531704  502.79079484 510.43538211 517.70587722
  524.6170264  531.17984596 537.40125349 543.28106749 548.80414244
  553.92348219 558.52992331 562.41656808 565.28841582 566.9158564
  567.43509564]
 [438.68841785 448.67466936 458.56327794 468.21647259 477.51461248
  486.39557717 494.84747803 502.88457447 510.52776884 517.79548411
  524.70186016

v:
 [[527.51321666 533.09912052 537.87872432 542.04680866 545.76564499
  549.14590622 552.25937192 555.15851812 557.88766422 560.47930246
  562.93550319 565.20277577 567.15558162 568.61600341 571.54274255
  574.27949558 576.81826082 579.16153785 580.02224659 580.34830292
  580.39004682]
 [523.77357065 529.59311887 534.62654692 539.0418871  542.99371556
  546.5905121  549.90443277 552.99104473 555.89788206 558.65724219
  561.26682599 563.6667808  565.72550229 567.26087041 570.13919672
  572.81903544 575.37544358 577.85813311 578.88607481 579.3418666
  579.44568622]
 [520.06328076 526.10471814 531.38414735 536.05001703 540.24331321
  544.06324902 547.57795988 550.8451015  553.9176709  556.83177206
  559.58438932 562.11113819 564.2739427  565.88397858 568.73936338
  571.28718609 573.60599536 575.79250795 576.93717439 577.44767791
  577.56582045]
 [516.41630116 522.67815521 528.20624099 533.13128431 537.57586255
  541.62364607 545.3339782  548.76541426 551.97943565 555.02150222
  557.89319

v:
 [[536.21308674 541.61249562 546.18636184 550.15346101 553.6825385
  556.89090013 559.86224558 562.66611661 565.36785575 568.02052254
  570.63669941 573.15013314 575.3893838  577.10355447 580.23879147
  583.11168308 585.67569061 587.95128028 588.90536975 589.2230847
  589.23322676]
 [533.20335405 538.78499531 543.55631328 547.72001888 551.43329244
  554.80679173 557.92280402 560.85376931 563.66875862 566.42147115
  569.12157462 571.69951275 573.98323877 575.72434631 579.01074654
  582.09437703 584.93056708 587.49052496 588.47967081 588.83087753
  588.85904548]
 [529.8623311  535.6529935  540.65630132 545.05700827 548.99664754
  552.57384239 555.86447482 558.94121833 561.87723155 564.72921923
  567.50667995 570.13906079 572.45594454 574.21402509 577.60781451
  580.8174405  583.82512755 586.60485407 587.62524148 588.00164315
  588.04202332]
 [526.27271357 532.30008132 537.57113059 542.2500178  546.45759205
  550.27384365 553.76214598 556.99247762 560.04356446 562.97972093
  565.815435

v:
 [[540.58000154 545.96495004 550.5227933  554.47356895 557.98684764
  561.18047037 564.13841752 566.9303023  569.62154372 572.26562251
  574.87599455 577.38719352 579.62750524 581.34428273 584.41677899
  587.23809181 589.76315567 592.01249831 592.95802708 593.26722566
  593.27270495]
 [537.67314288 543.23956153 547.9938737  552.14017938 555.83643082
  559.19378723 562.294856   565.2122689  568.01538151 570.75856223
  573.45252568 576.02849765 578.31394973 580.05834469 583.29405436
  586.33897076 589.14062093 591.66301266 592.63052058 592.95840974
  592.97339325]
 [534.43743644 540.21210175 545.19732663 549.57928828 553.50029297
  557.05950482 560.33322313 563.3944761  566.31692825 569.15816548
  571.92882653 574.55906392 576.87779254 578.63937066 581.99634267
  585.19179745 588.19655423 590.96656719 591.95658859 592.29880143
  592.31959186]
 [530.9522221  536.96274455 542.21453752 546.87319395 551.06038065
  554.85670973 558.32608873 561.53900248 564.57484742 567.49893057
  570.3268

v:
 [[543.47277508 548.84480779 553.38806092 557.32343016 560.82095363
  563.99864164 566.94037416 569.71540995 572.3886979  575.01347248
  577.60358578 580.09480955 582.31733543 584.02059931 587.04100899
  589.82115084 592.31759851 594.55029034 595.4838249  595.78675299
  595.79025931]
 [540.63604277 546.18912014 550.92835923 555.05882456 558.73892454
  562.07996732 565.16445822 568.0647038  570.8496716  573.57360356
  576.24769225 578.80436381 581.07282273 582.80435741 585.98844436
  588.9912269  591.75879769 594.25349602 595.2035208  595.51915645
  595.52872381]
 [537.47259954 543.23343914 548.20298998 552.56845289 556.47262488
  560.01486146 563.27141667 566.31507449 569.21922495 572.04143893
  574.79286214 577.40473523 579.70747543 581.45700544 584.76474391
  587.92316085 590.90030421 593.64753039 594.61668203 594.94290223
  594.95612151]
 [534.0595935  540.05565509 545.29098436 549.93225678 554.10170768
  557.88023454 561.33180443 564.52677325 567.54437877 570.44998249
  573.2596

v:
 [[545.40012427 550.76238948 555.29453827 559.21808521 562.70341591
  565.86867877 568.79770453 571.5595249  574.21877163 576.82850088
  579.40282972 581.87842367 584.08693389 585.77948234 588.76440479
  591.51662573 593.99386806 596.21562085 597.14054587 597.43925043
  597.44156262]
 [542.6108987  548.15393458 552.8817583  557.00012267 560.66777467
  563.99614462 567.06768384 569.95448675 572.72525436 575.43412843
  578.09262262 580.63403691 582.88892928 584.61011746 587.75827658
  590.73157777 593.47551024 595.95159381 596.8896748  597.19748949
  597.2037957 ]
 [539.49648159 545.24697418 550.20473015 554.55767689 558.44897115
  561.97811588 565.22134455 568.25127815 571.14111231 573.94839173
  576.68460623 579.28180137 581.5716003  583.31128728 586.58400288
  589.71524557 592.6716468  595.40215055 596.35730063 596.67350592
  596.6822118 ]
 [536.1325248  542.11784093 547.34087943 551.96908046 556.12508884
  559.89000886 563.32785272 566.50888604 569.51222734 572.40325994
  575.1983

v:
 [[546.68713175 552.04253356 556.56686129 560.48205865 563.95875722
  567.11520956 570.03522426 572.7876909  575.43703619 578.0362004
  580.59948041 583.06415016 585.26286597 586.94792473 589.90904786
  592.64256595 595.10697906 597.32146707 598.24053399 598.53641269
  598.53795056]
 [543.92985966 549.46585245 554.18564952 558.29547803 561.95432411
  565.27371092 568.33606378 571.2133443  573.97408192 576.67235496
  579.31989564 581.85060139 584.09596811 585.80988848 588.93382013
  591.88721436 594.61521994 597.07886122 598.0089181  598.31157645
  598.31577017]
 [540.84843825 546.59169035 551.54117237 555.88531043 559.76751341
  563.28739275 566.52117717 569.54138663 572.42109294 575.21782739
  577.94331561 580.53015755 582.81081939 584.54355217 587.792521
  590.90520367 593.84735905 596.56643028 597.51221567 597.82184889
  597.82763681]
 [537.51750865 543.49532836 548.70977223 553.32880325 557.47535009
  561.23066367 564.65879372 567.82995222 570.82318357 573.70389059
  576.4886922

v:
 [[550.04933559 555.65407417 560.5011395  564.53706934 568.67286815
  572.09803153 575.73581127 578.57681892 581.87064001 584.25537769
  587.29787709 590.14035744 592.79081758 595.24829777 597.4973934
  599.48252326 601.12356662 602.3165871  602.99054286 603.21870134
  603.29589459]
 [547.18199051 552.97715128 558.0248002  562.35183487 566.29406382
  570.40979271 573.74878052 577.36212594 580.17279875 583.44035312
  586.48629592 589.33132342 591.98760832 594.46294332 596.75305685
  598.78496208 600.47728306 601.7242463  602.44689471 602.71751536
  602.97037646]
 [544.03519195 550.0500725  555.32902798 559.85434792 564.06031924
  567.87138798 571.94837153 575.17640477 578.74247396 582.03515954
  585.09867367 587.95597809 590.626082   593.12763971 595.46767905
  597.56262733 599.3243189  600.6334427  601.39458455 601.81162691
  602.07413359]
 [540.67390951 546.92965842 552.4628328  557.16684759 561.57511997
  565.64713162 569.32948892 573.35303267 576.99808716 580.35399469
  583.46551

v:
 [[553.47189834 559.28845763 564.38753368 568.50940172 572.9191772
  576.40240548 580.31968062 583.17848566 586.74512645 589.11095179
  592.41175655 595.48605099 598.32676069 600.91890189 603.23827716
  605.24425137 606.87096696 608.03352344 608.68009858 608.88987008
  608.95769527]
 [550.5475738  556.55988373 561.86541381 566.34008525 570.43338339
  574.84049162 578.29883625 582.21221482 585.06207318 588.62384202
  591.9468231  595.03758696 597.88977847 600.48976252 602.81494839
  604.82657471 606.46158248 607.63899669 608.30811784 608.54029145
  608.79994134]
 [547.32322316 553.55522875 559.09105086 563.80769129 568.24223636
  572.29269148 576.69313873 580.11607971 584.0209417  587.64311475
  591.01429163 594.14087042 597.01830549 599.63591551 601.97430016
  603.99762196 605.64549846 606.83916527 607.5273724  608.06855561
  608.29556328]
 [543.87089462 550.33758161 556.11870353 561.03199102 565.7064875
  570.09330478 574.09876331 578.488715   582.50492861 586.22167423
  589.667703

v:
 [[555.03329911 560.89815197 566.05619348 570.18362477 574.65853066
  578.141593   582.12701223 584.979568   588.61612759 590.97235489
  594.344777   597.49202365 600.40510058 603.06682889 605.45060454
  607.51304791 609.18482161 610.37684801 611.03509662 611.24349322
  611.30376047]
 [552.11284701 558.1742299  563.53991287 568.03551083 572.15069258
  576.62505309 580.09771467 584.08217141 586.93102738 590.56621714
  593.9651424  597.13267885 600.06046204 602.7326152  605.12410037
  607.19314114 608.87207825 610.07345634 610.74323669 610.9617751
  611.20640358]
 [548.88723792 555.16801434 560.76384256 565.51474129 569.99308827
  574.08990773 578.56273401 582.02025185 586.00259391 589.70602405
  593.16045804 596.37031549 599.32882994 602.02298932 604.43098081
  606.51393258 608.20629613 609.42139361 610.10382706 610.64498697
  610.86117756]
 [545.42972754 551.94371483 557.78323222 562.73795515 567.47065044
  571.92837888 576.00532365 580.47571126 584.57838018 588.38514267
  591.92246

v:
 [[555.53022744 561.4010874  566.56702302 570.69025612 575.17443229
  578.653439   582.64917077 585.49796183 589.14580436 591.49894656
  594.88371879 598.04439487 600.97163139 603.64775746 606.04552491
  608.1207277  609.80296505 611.00194425 611.66297283 611.87106101
  611.9293066 ]
 [552.61698364 558.68452332 564.0583395  568.55209158 572.66654239
  577.15052224 580.62216253 584.61746124 587.46366419 591.11083526
  594.52304846 597.70494918 600.64780634 603.33522509 605.74147699
  607.82384213 609.51327909 610.72053111 611.39061217 611.60599181
  611.84590985]
 [549.3979131  555.68484651 561.28885349 566.0401433  570.52149613
  574.62276868 579.10606672 582.56686803 586.5611897  590.27809915
  593.74735255 596.97310921 599.94820314 602.65906754 605.08315052
  607.18053858 608.88405773 610.10479152 610.78616287 611.32420041
  611.53797871]
 [545.94631316 552.46629829 558.31382847 563.27010007 568.00827973
  572.47478233 576.56161744 581.04381583 585.16005094 588.98193959
  592.5357

v:
 [[556.46816768 562.3787992  567.57211556 572.23675612 576.50245163
  580.3473675  584.14778151 587.43832025 590.87377662 593.61875764
  596.76180072 599.07407377 601.96782299 604.62616227 607.02305473
  609.11154289 610.81509656 612.0349827  612.7090489  612.92080075
  612.97503527]
 [553.51683705 559.61754283 565.01478644 569.87893794 574.22436804
  578.48988303 582.32725085 586.12758182 589.41197891 592.84760526
  595.59068268 598.73379592 601.64843772 604.32328709 606.73348881
  608.83341336 610.5475615  611.77755787 612.46050172 612.6900575
  612.90309445]
 [550.26324726 556.57673833 562.20078323 567.28397091 571.86367636
  576.19849468 580.46349441 584.28948477 588.08956098 591.36493892
  594.80055653 597.99663165 600.95368119 603.66215215 606.09989507
  608.22388211 609.95993219 611.20888232 611.90537111 612.41384019
  612.63038322]
 [546.78439332 553.3246613  559.18919019 564.50226008 569.2684469
  573.83705904 578.1594462  582.42365228 586.23756785 590.03713929
  593.566349

v:
 [[556.73822973 562.65190989 567.84915379 572.51839486 576.78903381
  580.63264782 584.43787392 587.72692715 591.16663116 593.90988748
  597.05655687 599.36722069 602.26420904 604.925543   607.32529473
  609.41654911 611.12260388 612.34426461 613.0189617  613.23043765
  613.28384294]
 [553.79078333 559.89440516 565.29545916 570.16413901 574.51010912
  578.78068249 582.61932379 586.4244469  589.70937931 593.14896121
  595.89082197 599.03732965 601.95500849 604.63268979 607.04564685
  609.148261   610.86473295 612.09597044 612.77850132 613.00546247
  613.21785241]
 [550.54085194 556.85706098 562.48470683 567.57223473 572.15400829
  576.49300313 580.7633347  584.59449618 588.39933578 591.67822545
  595.11751889 598.31664044 601.27634105 603.98729908 606.42752639
  608.55400584 610.2922006  611.54206827 612.23753088 612.74539953
  612.96082911]
 [547.06544337 553.6081482  559.47596332 564.79306312 569.56178392
  574.13617683 578.46684692 582.73672725 586.55977737 590.36415766
  593.8972

v:
 [[556.95076475 562.86507027 568.06331468 572.73396542 577.0063782
  580.84725756 584.65441784 587.94109515 591.38276209 594.12410656
  597.27274064 599.58206472 602.48105001 605.14442831 607.54620118
  609.63933784 611.34694829 612.5695873  613.24453644 613.45576382
  613.50853447]
 [554.00739383 560.11163559 565.51370814 570.38384487 574.72778915
  579.00019514 582.83741311 586.64454517 589.92820492 593.36981944
  596.11013307 599.25867366 602.17846064 604.85828614 607.27335435
  609.37791012 611.09588342 612.32776739 613.00985477 613.23469263
  613.44658359]
 [550.76151173 557.07831847 562.70697009 567.79595282 572.3763109
  576.71509707 580.98742726 584.81915278 588.62617606 591.90536847
  595.34683918 598.54820655 601.51019747 604.22346068 606.66594784
  608.7944996  610.53425673 611.78464803 612.47928893 612.98574708
  613.20034308]
 [547.29011987 553.83337899 559.70215044 565.02064978 569.78818
  574.36308261 578.69570563 582.967871   586.79356591 590.60039641
  594.13602582 